# 网站标题
title: Note
# 网站标题后缀
suffix: Junixcn
# 作者名称(会显示在首页文章下面)
author: Junixcn
# 首页简介（显示在首页顶部Logo的那句话）
home_describe: 智慧夯实基础 坚持成就未来
# 网站关键字
keyword: Notes
is_article_img: true  #false是否开启文章背景图显示(随机图片)
# 网站描述
web_description: 描述
# 导航名称
menus_title:
  home: 主页
  archive: 列表
  categories: 分类
  tags: 标签
  links: 链接
  about: 关于
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# logo
logo: /image/logo.png
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面上面的图表
topIcon:
  homeIcon: "/image/logo.png"
  archivesIcon: "/image/logo.png"
  tagIcon: "/image/logo.png"
  linksIcon: "/image/logo.png"
  categoriesIcon: "/image/logo.png"
  
# 标签页显示多少个标签
tagsNum: 20
# 网页访问统计
web_analytics:  
  enable: true #需要改为true
  baidu: 4b5fe1472f22fa  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: '/image/github-logo.png',
    #跳转链接   
    toUrl: 'https://github.com/junixcn'
  }
# 友情链接
linksList:
  - {
    title: 'google',
    intro: 'google',
    link: 'https://www.google.com',
    image: ''
  }
  - {
    title: 'baidu',
    intro: 'baidu',
    link: 'https://www.baidu.com',
    image: ''
  }
# 文字内点击图片放大相关配置
picture:
  # 蒙版的颜色也就是 打开图片背景 显示的颜色
  colour: '#333'
  # 透明度
  opacity: 0.5
  # 图片角度 就是显示图片的角度
  imgRadius: "10px"
#默认的cover (默认缩略图) 在没有填写
default_cover: 
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img10.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img11.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img12.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img13.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img14.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img15.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img16.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img17.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img18.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img19.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img20.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img21.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img22.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img23.jpg
  - https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/img24.jpg
